-- Migration V26: Champion/Challenger registry for TrainML gating
-- Supports walk-forward validation audit trail and automatic rollback metadata.

CREATE TABLE IF NOT EXISTS ml_model_registry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_type TEXT NOT NULL,              -- classifier, regressor, lstm
    model_version TEXT NOT NULL,
    role TEXT NOT NULL,                    -- CHAMPION or CHALLENGER
    is_active BOOLEAN DEFAULT FALSE,       -- True only for active champion row
    gate_status TEXT NOT NULL,             -- PASS, ROLLED_BACK, FAIL
    validation_method TEXT,                -- walk_forward
    metric_name TEXT,                      -- accuracy, directional_accuracy, ...
    candidate_metric DOUBLE PRECISION,
    baseline_metric DOUBLE PRECISION,
    champion_metric DOUBLE PRECISION,
    improvement_abs DOUBLE PRECISION,
    degradation_vs_champion DOUBLE PRECISION,
    replaced_version TEXT,
    notes TEXT,
    trained_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_ml_registry_type_time
    ON ml_model_registry(model_type, trained_at DESC);

CREATE INDEX IF NOT EXISTS idx_ml_registry_active
    ON ml_model_registry(model_type, role, is_active);

