-- Migration V23: AI Performance Feedback Loop
-- Records AI suggestions and tracks their success over time

CREATE TABLE IF NOT EXISTS ai_performance_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker TEXT NOT NULL,
    action_type TEXT NOT NULL, -- 'BUY', 'ACCUMULATE', 'TRIM', 'SELL'
    price_at_suggestion DECIMAL(12,2) NOT NULL,
    current_price DECIMAL(12,2),
    performance_pct DECIMAL(12,4), -- (Current - Suggestion) / Suggestion
    is_win BOOLEAN, -- Performance matches action (e.g. BUY + UP = WIN)
    suggestion_data JSONB, -- Context data
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    evaluated_at TIMESTAMP WITH TIME ZONE
);

CREATE INDEX IF NOT EXISTS idx_ai_perf_ticker ON ai_performance_logs(ticker);
CREATE INDEX IF NOT EXISTS idx_ai_perf_date ON ai_performance_logs(created_at);
