-- Migration v25: Hunt Contracts Alignment
-- Goals:
-- 1) Align predictions schema with app payload (`source_url`, WATCH/AVOID sentiments)
-- 2) Add social_stats table used by Social Oracle velocity features

DO $$
DECLARE
    sentiment_constraint_name TEXT;
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'predictions'
    ) THEN
        -- Ensure unified source link column exists.
        IF NOT EXISTS (
            SELECT 1
            FROM information_schema.columns
            WHERE table_schema = 'public' AND table_name = 'predictions' AND column_name = 'source_url'
        ) THEN
            ALTER TABLE public.predictions ADD COLUMN source_url TEXT;
        END IF;

        -- Backfill source_url from legacy columns when present.
        IF EXISTS (
            SELECT 1
            FROM information_schema.columns
            WHERE table_schema = 'public' AND table_name = 'predictions' AND column_name = 'source_news_url'
        ) THEN
            EXECUTE 'UPDATE public.predictions
                     SET source_url = COALESCE(source_url, source_news_url)
                     WHERE source_url IS NULL';
        END IF;

        IF EXISTS (
            SELECT 1
            FROM information_schema.columns
            WHERE table_schema = 'public' AND table_name = 'predictions' AND column_name = 'url'
        ) THEN
            EXECUTE 'UPDATE public.predictions
                     SET source_url = COALESCE(source_url, url)
                     WHERE source_url IS NULL';
        END IF;

        -- Replace any legacy sentiment CHECK with an expanded one.
        FOR sentiment_constraint_name IN
            SELECT conname
            FROM pg_constraint
            WHERE conrelid = 'public.predictions'::regclass
              AND contype = 'c'
              AND pg_get_constraintdef(oid) ILIKE '%sentiment%'
        LOOP
            EXECUTE format('ALTER TABLE public.predictions DROP CONSTRAINT %I', sentiment_constraint_name);
        END LOOP;

        ALTER TABLE public.predictions
            ADD CONSTRAINT predictions_sentiment_check
            CHECK (sentiment IN ('BUY', 'SELL', 'HOLD', 'ACCUMULATE', 'PANIC SELL', 'WATCH', 'AVOID'));
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS public.social_stats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker VARCHAR(20) NOT NULL,
    mentions INTEGER NOT NULL DEFAULT 0 CHECK (mentions >= 0),
    source VARCHAR(20) NOT NULL DEFAULT 'reddit',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_social_stats_ticker_created_at
    ON public.social_stats (ticker, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_social_stats_created_at
    ON public.social_stats (created_at DESC);

GRANT SELECT, INSERT ON public.social_stats TO anon;
GRANT SELECT, INSERT ON public.social_stats TO authenticated;
