-- Create portfolio table
create table portfolio (
  id bigint generated by default as identity primary key,
  ticker text not null unique,
  avg_price numeric,
  quantity numeric,
  sector text
);

-- Enable Row Level Security (RLS)
alter table portfolio enable row level security;

-- Create Policy: Allow read access to everyone (or specific roles)
create policy "Allow public read access" on portfolio
  for select using (true);

-- Create Policy: Allow write access to service_role only (for now)
create policy "Allow service_role write access" on portfolio
  for all using (auth.role() = 'service_role');
