-- Migration V22: ML Health Monitoring
-- Tracks success and failure rates of ML predictions

CREATE TABLE IF NOT EXISTS ml_health_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_type TEXT NOT NULL, -- 'classifier', 'regressor', 'lstm'
    status TEXT NOT NULL,     -- 'SUCCESS', 'FAILURE'
    error_msg TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Index for efficient querying by date and model
CREATE INDEX IF NOT EXISTS idx_ml_health_date ON ml_health_logs(created_at);
CREATE INDEX IF NOT EXISTS idx_ml_health_model ON ml_health_logs(model_type);
